// Copyright 2020-2023 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= Contributing

Contributions to the Vulkan-Site repository are welcome.

Contributions may be in the form of Issues proposing a change, or Pull
Requests containing fixes, for the Antora playbook and related files.

Issues with the underlying documentation components should be raised in the
appropriate repositories (KhronosGroup/Vulkan-Docs for the Vulkan
specification and proposals, and KhronosGroup/Vulkan-Guide for the Vulkan
Guide).


Please keep contributions focused on solving a single issue or bug.

== Copyright Notice and License Template

If you are adding a new file, it must be under one of the following
licenses:

  * Creative Commons Attribution 4.0 International, for documentation (such
    as this link:CONTRIBUTING.adoc[`CONTRIBUTING`] file).
  * Apache 2.0, for scripts, code, build tools, and all other changes (for
    example, link:docs-site/Makefile[`Makefile`]

We use a short license in each file consisting of just the copyright
statement and the SPDX license identifier of the license applying to that
file, and link to the full license text from
link:LICENSE.adoc[`LICENSE.adoc`].

== Contributor License Agreement

When you propose a pull request on Vulkan-Site you must execute the Khronos
Mixed Repository Contributor License Agreement, to confirm you own your work
and are granting Khronos the necessary permissions to redistribute it under
our licenses.
