// Copyright 2020-2023 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= COPYING file for the KhronosGroup/Vulkan-Site project

== Licenses

The Vulkan-Site project uses several licenses.

* Documentation files (in asciidoctor and other formats) are licensed under
  the Creative Commons Attribution 4.0 International License (SPDX license
  identifier "`CC-BY-4.0`").
* Scripts, programs, and other tooling used or generated as part of the
  build process are typically licensed under the Apache License, Version 2.0
  (SPDX license identifier "`Apache-2.0`").
* Per recommended Antora practice, the entire Antora tool, and its many
  JavaScript module dependencies, are included in the repository under
  link:docs-site/node_modules/. These files are installed via `npm` and come
  under a variety of licenses of their own, which we do not currently
  summarize here. If we at some point include modules authored by Khronos
  under `node_modules`, they will be placed under Apache 2.0.
