// Copyright 2023-2026 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= LICENSE file for the KhronosGroup/Vulkan-Site project

This project combines files from several other repositories with
Khronos-authored files to form the build environment for the
link:https://docs.vulkan.org/[Vulkan Documentation Project].

Files are under a mix of licenses.

  * The site UI is derived from the
    link:https://gitlab.com/antora/antora-ui-default[Antora Default UI]
    project, which files are under the MPL-2.0 (Mozilla Public License
    Version 2.0).
  * Some Javascript plugins for source code highlighting are derived from
    the link:https://github.com/highlightjs/highlightjs-hlsl[HighlightJS]
    project and are under an MIT license.
  * The asciidoctor-mathjax extension is derived from the
    link:https://gitlab.com/djencks/asciidoctor-mathjax.js[asciidoctor-mathjax.js]
    project which is under an MIT license.
  * Solely Khronos-authored scripts, code, and build tools are under the
    Apache-2.0 (Apache License 2.0).
  * Solely Khronos-authored documentation is under the CC-BY-4.0 (Creative
    Commons Attribution 4.0 International) license.
  * Where Khronos has modified files from upstream repositories, we add a
    Khronos attribution to the copyright statement while retaining the
    original license.

Full license text is available in the LICENSES/ subdirectory.

A complete license manifest of this project can be obtained using the
link:https://reuse.software/[REUSE] tool, which is incorporated into project
CI to ensure all files are licensed.
Upstream files, images, and other files without imbedded copyright
statements are given license attributions in the link:REUSE.toml file.
