version = 1
SPDX-PackageName = "Vulkan-Site"
SPDX-PackageDownloadLocation = "https://github.com/KhronosGroup/Vulkan-Site"

# Upstream Antora Default UI files
[[annotations]]
path = ["docs/**", "gulp.d/**", "preview-src/**", "src/**", ".editorconfig", ".eslintrc", ".gitignore", ".gitlab-ci.yml", ".gulp.json", ".nvmrc", ".stylelintrc", "gulpfile.js", "index.js", "package-lock.json", "package.json"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2017-present OpenDevise Inc. and the Antora Project."
SPDX-License-Identifier = "MPL-2.0"

# Upstream UI files with substantial Khronos modifications
[[annotations]]
path = ["README.adoc", "src/css/base.css", "src/css/doc.css", "src/css/header.css", "src/css/highlight.css", "src/css/site.css", "src/css/toolbar.css", "src/css/vars.css"]
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright (C) 2017-present OpenDevise Inc. and the Antora Project.", "Copyright 2023-2026 The Khronos Group Inc."]
SPDX-License-Identifier = "MPL-2.0"

# asciidoctor-mathjax extension
[[annotations]]
path = "docs-site/js/asciidoctor-mathjax.js"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (c) 2020 David Jencks and contributors"
SPDX-License-Identifier = "MIT"

# Khronos scripts and code
[[annotations]]
path = [".eslintignore", "src/css/khronos.css", "src/css/split.css", "src/css/vendor/tabs.css", "src/js/20-multilang.js", "src/js/vendor/split.js", "src/js/vendor/tabs.bundle.js", "docs-site/package-lock.json", "docs-site/package.json"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright 2023-2026 The Khronos Group Inc."
SPDX-License-Identifier = "Apache-2.0"

# Khronos documentation
[[annotations]]
path = [".github/**", "src/static/**"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright 2023-2026 The Khronos Group Inc."
SPDX-License-Identifier = "CC-BY-4.0"

