# Copyright 2022-2023 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

site:
  title: Vulkan Documentation Project Demo
  start_page: spec::index.adoc
content:
# Use worktree for guide and spec - local file URL, HEAD branch, not
# specifying .git directory (on antora branch)
  sources:
    - url: /home/tree/git/Vulkan-Guide
      branches: HEAD
      start_path: antora
    - url: /home/tree/git/Vulkan-Docs
      branches: HEAD
      start_path: antora
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
asciidoc:
  extensions:
    # specmacros.js requires './apimap.cjs', 'xrefMap.cjs', and 'pageMap.cjs'.
    # These are generated in the Vulkan Antora spec source tree in the
    # `antora/Makefile` `install_maps` target as part of preparing spec
    # source in that repository, and must be copied to `js/` here before
    # running the playbook.
    # Hopefully we can use Antora Collector for all of this preparation
    # in the future.
    - ./js/specmacros.js
    - '@djencks/asciidoctor-mathjax'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
