# Copyright 2026 Holochip, Inc.
# SPDX-License-Identifier: Apache-2.0

name: antora-static-nav

on:
  push:
    paths:
      - 'docs-site/extensions/antora-static-nav/**'
  pull_request:
    paths:
      - 'docs-site/extensions/antora-static-nav/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      - name: "Run tests"
        working-directory: docs-site/extensions/antora-static-nav
        run: node --test test/
